package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author ALEJO
 */
public class InformacionEquipo extends javax.swing.JFrame {
    
    String user = "", user_update = "", equipo_update="";
    int ID;
    String fechaIngreso;

    /**
     * Creates new form InformacionEquipo
     */
    public InformacionEquipo() {
        initComponents();
        user = Login.user;
        user_update = GestionarClientes.user_update;
        equipo_update = InformacionCliente.equipo_update;
        

        setSize(641, 447);
        setResizable(false); 
        setTitle("Información del equipo " + " - Sesión de " + user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);
        this.repaint();
        
        jLabel1.setText("Información de Equipo");
        txt_nombreCliente.setText(user_update);
        
        
        //traemos la info de la bd de equipos
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select * from equipos where tipo_equipo = '" + equipo_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                ID = rs.getInt("id_equipo");
                
                cmb_tipoEquipo.setSelectedItem(rs.getString("tipo_equipo"));
                cmb_estatus.setSelectedItem(rs.getString("estatus"));
                cmb_marca.setSelectedItem(rs.getString("marca"));
                
                
                txt_modelo.setText(rs.getString("modelo"));
                txt_noSerie.setText(rs.getString("num_serie"));
                txt_ultmodificPor.setText(rs.getString("ultima_modificacion"));
                txt_fechaIngreso.setText(rs.getString("fecha_ingreso"));
                txt_observaciones.setText(rs.getString("observaciones"));
                
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error en cargar cliente. " + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al cargar!!, contacte al administrador.");
        }
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_tipoEquipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmb_marca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_noSerie = new javax.swing.JTextField();
        jButton_actualizarEquipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jLabel_footer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comentariosTecnicos = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_fechaIngreso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_ultmodificPor = new javax.swing.JTextField();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informacion del equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txt_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreCliente.setEnabled(false);
        txt_nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daño reportado y observaciones:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        cmb_tipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(cmb_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Acer", "HP", "Lenovo", "Sony" }));
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modeloActionPerformed(evt);
            }
        });
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("N° de serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txt_noSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_noSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_noSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_noSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_noSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_noSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, -1));

        jButton_actualizarEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jButton_actualizarEquipo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_actualizarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizarEquipo.setText("Actualizar Equipo");
        jButton_actualizarEquipo.setBorder(null);
        jButton_actualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 210, 35));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 290, 90));

        jLabel_footer.setText("Creado por La Geekipedia de Ernesto ®");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        txt_comentariosTecnicos.setColumns(20);
        txt_comentariosTecnicos.setRows(5);
        txt_comentariosTecnicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_comentariosTecnicos.setEnabled(false);
        jScrollPane2.setViewportView(txt_comentariosTecnicos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 290, 90));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Equipo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comentarios y actualizacion del tecnico:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de ingreso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 20));

        txt_fechaIngreso.setBackground(new java.awt.Color(153, 153, 255));
        txt_fechaIngreso.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_fechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        txt_fechaIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fechaIngreso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_fechaIngreso.setEnabled(false);
        txt_fechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Estatus:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo Ingreso", "No Reparado", "En Revision", "Reparado", "Entregado" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ultima modificacion por:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txt_ultmodificPor.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultmodificPor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ultmodificPor.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultmodificPor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultmodificPor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ultmodificPor.setEnabled(false);
        txt_ultmodificPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultmodificPorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ultmodificPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 210, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 641, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreClienteActionPerformed

    }//GEN-LAST:event_txt_nombreClienteActionPerformed

    private void txt_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modeloActionPerformed

    private void jButton_actualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarEquipoActionPerformed

        int tipoEq_cmb, marca_cmb, estatus_cmb = 0, validacion = 0;
        String  modelo, noSerie, observaciones, tipoEquipo_string = "", Marca_string = "", estatus_string = "";

        noSerie = txt_noSerie.getText().trim();
        modelo = txt_modelo.getText().trim();
        marca_cmb = cmb_marca.getSelectedIndex() + 1;
        tipoEq_cmb = cmb_tipoEquipo.getSelectedIndex() + 1;
        estatus_cmb = cmb_estatus.getSelectedIndex() + 1;
        observaciones = txt_observaciones.getText().trim();

        if(noSerie.equals("")){
            txt_noSerie.setBackground(Color.red);
            validacion++;
        }
        if(modelo.equals("")){
            txt_modelo.setBackground(Color.red);
            validacion++;
        }
        if(observaciones.equals("")){
            txt_observaciones.setBackground(Color.red);
            validacion++;
        }

        if(marca_cmb == 1){
            Marca_string = "Apple";
        } else if(marca_cmb == 2){
            Marca_string = "Acer";
        } else if(marca_cmb == 3){
            Marca_string = "HP";
        } else if(marca_cmb == 4){
            Marca_string = "Lenovo";
        } else if(marca_cmb == 5){
            Marca_string = "Sony";
        }

        if(tipoEq_cmb == 1){
            tipoEquipo_string = "Laptop";
        } else if(tipoEq_cmb == 2){
            tipoEquipo_string = "Desktop";
        } else if(tipoEq_cmb == 3){
            tipoEquipo_string = "Impresora";
        } else if(tipoEq_cmb == 4){
            tipoEquipo_string = "Multifuncional";
        }
        
        if(estatus_cmb == 1){
            estatus_string = "Nuevo Ingreso";
        } else if(estatus_cmb == 2){
            estatus_string = "No Reparado";
        } else if(estatus_cmb == 3){
            estatus_string = "En Revision";
        } else if(estatus_cmb == 4){
            estatus_string = "Reparado";
        } else if(estatus_cmb == 5){
            estatus_string = "Entregado";
        }

        

        if (validacion == 0) {

            try{
                  
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("update equipos set tipo_equipo ='"+tipoEquipo_string+"',marca='"+Marca_string+"',modelo='"+txt_modelo.getText()+"',num_serie='"+txt_noSerie.getText()+"',"
                   +"estatus='"+estatus_string+"',ultima_modificacion='"+user+"',observaciones='"+txt_observaciones.getText()+"'where id_equipo ='"+ID+"'");
                 
                pst.executeUpdate();
                cn.close();
           
                System.out.println("Registro Exitoso");
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
                this.dispose();
           
                            
            }catch(SQLException e){
                System.err.println("Error al Actualizar el usuario." + e);
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
            
        }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }
    }//GEN-LAST:event_jButton_actualizarEquipoActionPerformed

    private void txt_fechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaIngresoActionPerformed

    private void txt_ultmodificPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultmodificPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultmodificPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoEquipo;
    private javax.swing.JButton jButton_actualizarEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JTextArea txt_comentariosTecnicos;
    private javax.swing.JTextField txt_fechaIngreso;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_noSerie;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextArea txt_observaciones;
    private javax.swing.JTextField txt_ultmodificPor;
    // End of variables declaration//GEN-END:variables
}
