/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import static ventanas.Administrador.sesion_usuario;

/**
 *
 * @author ALEJO
 */
public class RecuperarPassword extends javax.swing.JFrame {

    String user = "", user_update = "";
    int ID;
    public static int sesion_usuario;
    /**
     * Creates new form RecuperarPassword
     */
    public RecuperarPassword() {
        initComponents();
        user = Login.user;
        sesion_usuario = 1;
        user_update = GestionarUsuarios.user_update;
        
        setSize(280, 220);
        setResizable(false);
        setTitle("Cambio de password - Sesión de " + user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lbl_wallpaper.getWidth(),
                lbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        lbl_wallpaper.setIcon(icono);
        this.repaint();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        txt_contraseña = new javax.swing.JPasswordField();
        txt_nvaContraseña = new javax.swing.JPasswordField();
        lbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambio de Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnEnviar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(102, 102, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, 30));

        txt_contraseña.setBackground(new java.awt.Color(153, 153, 255));
        txt_contraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, -1));

        txt_nvaContraseña.setBackground(new java.awt.Color(153, 153, 255));
        txt_nvaContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nvaContraseña.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_nvaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));
        getContentPane().add(lbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo del boton Enviar
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        String contraseña, nvaContraseña;
        int validacion = 0;
        
        //Recibe la info del inputText
        contraseña = txt_contraseña.getText().trim();
        nvaContraseña = txt_nvaContraseña.getText().trim();
        
        //Validamos que los campos no sean enviados en blanco
        if(contraseña.equals("")){
            txt_contraseña.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
            validacion++;
        }
        if(nvaContraseña.equals("")){
            txt_nvaContraseña.setBackground(Color.red);
            validacion++;
        }
        
        try{
            //Traemos el usuario al cual se le cmabiara la clave      
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where username = '" + user_update + "'");
            ResultSet rs = pst.executeQuery();
           
            if(rs.next()){
                ID = rs.getInt("id_usuario");
            }
             cn.close();
        
        }catch(SQLException e){
                System.err.println("Error en cargar usuario. " + e);
            }
        
        //Garantizamos que tanto la contraseña como la nva contraseña tengan la misma informacion
        if (validacion == 0) {     
            
            if(contraseña.equals(nvaContraseña)){
                
                try{
                  
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("update usuarios set password ='"+txt_contraseña.getText()+"'where id_usuario ='"+ID+"'");
                pst.executeUpdate();
                cn.close();
           
                System.out.println("Registro Exitoso");
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
                this.dispose();
           
                            
                }catch(SQLException e){
                    System.err.println("Error al Actualizar contraseña." + e);
                    JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Los datos ingresados no coinciden, intente nuevamente");
            }  
    }//GEN-LAST:event_btnEnviarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JPasswordField txt_nvaContraseña;
    // End of variables declaration//GEN-END:variables
}
